name: layerx_fire_chat
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.10
  firebase_storage: ^12.4.8
  photo_view: ^0.15.0
  url_launcher: ^6.2.1

  flutter_link_previewer: ^3.2.2
  firebase_auth: ^5.0.0
  rxdart: any
  shimmer: any
  logger: ^2.6.1
  cupertino_icons: ^1.0.8
  layerx_generator: ^2.0.0
  connectivity_plus: ^6.1.4
  http: ^1.3.0
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  file_picker: ^10.1.2
  permission_handler:
  image_picker:
  animate_do:
  get_storage:
  custom_cached_image: ^1.2.0
  smooth_page_indicator:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/svgs/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
